<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>$schema</key>
	<string>https://raw.githubusercontent.com/martinring/tmlanguage/master/tmlanguage.json</string>
	<key>fileTypes</key>
	<array>
		<string>uflow</string>
	</array>
	<key>name</key>
	<string>UFlow</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#expression</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>case</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>string</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#control</string>
						</dict>
					</array>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s*(~|CASE\s+)(.*)</string>
		</dict>
		<key>comment</key>
		<dict>
			<key>match</key>
			<string>#.*</string>
			<key>name</key>
			<string>comment</string>
		</dict>
		<key>context</key>
		<dict>
			<key>match</key>
			<string>\[.*]</string>
			<key>name</key>
			<string>keyword.control</string>
		</dict>
		<key>control</key>
		<dict>
			<key>match</key>
			<string>IF|THEN|ELSE|END|WHEN|EXIT|FLOW|GOTO|RUN|LABEL|DO|WHILE|SWITCH|CASES|CASE|BREAK|ALL|ANY|OTHER|DEFAULT|AND|OR|NOT</string>
			<key>name</key>
			<string>keyword.control</string>
		</dict>
		<key>control-logic</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control</string>
				</dict>
				<key>2</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#expression</string>
						</dict>
					</array>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.control</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(IF|ELSE\s+IF|WHEN)(.*)(THEN|IS)</string>
		</dict>
		<key>control-named</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.class</string>
				</dict>
				<key>3</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#expression</string>
						</dict>
					</array>
				</dict>
			</dict>
			<key>match</key>
			<string>(FLOW|GOTO|RUN|LABEL)\s*(\w+)(.*)</string>
		</dict>
		<key>embedded_block_c</key>
		<dict>
			<key>begin</key>
			<string>```\s*c</string>
			<key>contentName</key>
			<string>meta.embedded.block.c</string>
			<key>end</key>
			<string>```</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.c</string>
				</dict>
			</array>
		</dict>
		<key>embedded_block_clojure</key>
		<dict>
			<key>begin</key>
			<string>```\s*clojure</string>
			<key>contentName</key>
			<string>meta.embedded.block.clojure</string>
			<key>end</key>
			<string>```</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.clojure</string>
				</dict>
			</array>
		</dict>
		<key>embedded_block_coffee</key>
		<dict>
			<key>begin</key>
			<string>```\s*coffee</string>
			<key>contentName</key>
			<string>meta.embedded.block.coffee</string>
			<key>end</key>
			<string>```</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.coffee</string>
				</dict>
			</array>
		</dict>
		<key>embedded_block_cpp</key>
		<dict>
			<key>begin</key>
			<string>```\s*cpp</string>
			<key>contentName</key>
			<string>meta.embedded.block.cpp</string>
			<key>end</key>
			<string>```</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.cpp</string>
				</dict>
			</array>
		</dict>
		<key>embedded_block_csharp</key>
		<dict>
			<key>begin</key>
			<string>```\s*csharp</string>
			<key>contentName</key>
			<string>meta.embedded.block.csharp</string>
			<key>end</key>
			<string>```</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.cs</string>
				</dict>
			</array>
		</dict>
		<key>embedded_block_css</key>
		<dict>
			<key>begin</key>
			<string>```\s*css</string>
			<key>contentName</key>
			<string>meta.embedded.block.css</string>
			<key>end</key>
			<string>```</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.css</string>
				</dict>
			</array>
		</dict>
		<key>embedded_block_diff</key>
		<dict>
			<key>begin</key>
			<string>```\s*diff</string>
			<key>contentName</key>
			<string>meta.embedded.block.diff</string>
			<key>end</key>
			<string>```</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.diff</string>
				</dict>
			</array>
		</dict>
		<key>embedded_block_dockerfile</key>
		<dict>
			<key>begin</key>
			<string>```\s*dockerfile</string>
			<key>contentName</key>
			<string>meta.embedded.block.dockerfile</string>
			<key>end</key>
			<string>```</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.dockerfile</string>
				</dict>
			</array>
		</dict>
		<key>embedded_block_dosbatch</key>
		<dict>
			<key>begin</key>
			<string>```\s*bat</string>
			<key>contentName</key>
			<string>meta.embedded.block.dosbatch</string>
			<key>end</key>
			<string>```</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.batchfile</string>
				</dict>
			</array>
		</dict>
		<key>embedded_block_frontmatter</key>
		<dict>
			<key>begin</key>
			<string>```\s*(yaml|yml)</string>
			<key>contentName</key>
			<string>meta.embedded.block.frontmatter</string>
			<key>end</key>
			<string>```</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.yaml</string>
				</dict>
			</array>
		</dict>
		<key>embedded_block_fsharp</key>
		<dict>
			<key>begin</key>
			<string>```\s*fsharp</string>
			<key>contentName</key>
			<string>meta.embedded.block.fsharp</string>
			<key>end</key>
			<string>```</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.fsharp</string>
				</dict>
			</array>
		</dict>
		<key>embedded_block_go</key>
		<dict>
			<key>begin</key>
			<string>```\s*go</string>
			<key>contentName</key>
			<string>meta.embedded.block.go</string>
			<key>end</key>
			<string>```</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.go</string>
				</dict>
			</array>
		</dict>
		<key>embedded_block_groovy</key>
		<dict>
			<key>begin</key>
			<string>```\s*groovy</string>
			<key>contentName</key>
			<string>meta.embedded.block.groovy</string>
			<key>end</key>
			<string>```</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.groovy</string>
				</dict>
			</array>
		</dict>
		<key>embedded_block_html</key>
		<dict>
			<key>begin</key>
			<string>```\s*html</string>
			<key>contentName</key>
			<string>text.html.basic</string>
			<key>end</key>
			<string>```</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>text.html.basic</string>
				</dict>
			</array>
		</dict>
		<key>embedded_block_ini</key>
		<dict>
			<key>begin</key>
			<string>```\s*ini</string>
			<key>contentName</key>
			<string>meta.embedded.block.ini</string>
			<key>end</key>
			<string>```</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.ini</string>
				</dict>
			</array>
		</dict>
		<key>embedded_block_java</key>
		<dict>
			<key>begin</key>
			<string>```\s*java</string>
			<key>contentName</key>
			<string>meta.embedded.block.java</string>
			<key>end</key>
			<string>```</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.java</string>
				</dict>
			</array>
		</dict>
		<key>embedded_block_javascript</key>
		<dict>
			<key>begin</key>
			<string>```\s*(js|jsx|javascript|es6|mjs|cjs)</string>
			<key>contentName</key>
			<string>meta.embedded.block.javascript</string>
			<key>end</key>
			<string>```</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.js</string>
				</dict>
			</array>
		</dict>
		<key>embedded_block_json</key>
		<dict>
			<key>begin</key>
			<string>```\s*json</string>
			<key>contentName</key>
			<string>meta.embedded.block.json</string>
			<key>end</key>
			<string>```</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.json</string>
				</dict>
			</array>
		</dict>
		<key>embedded_block_jsonc</key>
		<dict>
			<key>begin</key>
			<string>```\s*jsonc</string>
			<key>contentName</key>
			<string>meta.embedded.block.jsonc</string>
			<key>end</key>
			<string>```</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.json.comments</string>
				</dict>
			</array>
		</dict>
		<key>embedded_block_less</key>
		<dict>
			<key>begin</key>
			<string>```\s*less</string>
			<key>contentName</key>
			<string>meta.embedded.block.less</string>
			<key>end</key>
			<string>```</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.css.less</string>
				</dict>
			</array>
		</dict>
		<key>embedded_block_lua</key>
		<dict>
			<key>begin</key>
			<string>```\s*lua</string>
			<key>contentName</key>
			<string>meta.embedded.block.lua</string>
			<key>end</key>
			<string>```</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.lua</string>
				</dict>
			</array>
		</dict>
		<key>embedded_block_makefile</key>
		<dict>
			<key>begin</key>
			<string>```\s*makefile</string>
			<key>contentName</key>
			<string>meta.embedded.block.makefile</string>
			<key>end</key>
			<string>```</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.makefile</string>
				</dict>
			</array>
		</dict>
		<key>embedded_block_objc</key>
		<dict>
			<key>begin</key>
			<string>```\s*objc</string>
			<key>contentName</key>
			<string>meta.embedded.block.objc</string>
			<key>end</key>
			<string>```</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.objc</string>
				</dict>
			</array>
		</dict>
		<key>embedded_block_perl</key>
		<dict>
			<key>begin</key>
			<string>```\s*perl</string>
			<key>contentName</key>
			<string>meta.embedded.block.perl</string>
			<key>end</key>
			<string>```</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.perl</string>
				</dict>
			</array>
		</dict>
		<key>embedded_block_perl6</key>
		<dict>
			<key>begin</key>
			<string>```\s*(perl6|p6|pl6|pm6|nqp)</string>
			<key>contentName</key>
			<string>meta.embedded.block.perl6</string>
			<key>end</key>
			<string>```</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.perl.6</string>
				</dict>
			</array>
		</dict>
		<key>embedded_block_php</key>
		<dict>
			<key>begin</key>
			<string>```\s*php</string>
			<key>contentName</key>
			<string>meta.embedded.block.php</string>
			<key>end</key>
			<string>```</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.php</string>
				</dict>
				<dict>
					<key>include</key>
					<string>text.html.basic</string>
				</dict>
			</array>
		</dict>
		<key>embedded_block_powershell</key>
		<dict>
			<key>begin</key>
			<string>```\s*(powershell|ps1)</string>
			<key>contentName</key>
			<string>meta.embedded.block.powershell</string>
			<key>end</key>
			<string>```</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.powershell</string>
				</dict>
			</array>
		</dict>
		<key>embedded_block_pug</key>
		<dict>
			<key>begin</key>
			<string>```\s*(jade|pug)</string>
			<key>contentName</key>
			<string>meta.embedded.block.pug</string>
			<key>end</key>
			<string>```</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>text.pug</string>
				</dict>
			</array>
		</dict>
		<key>embedded_block_python</key>
		<dict>
			<key>begin</key>
			<string>```\s*(python|py)</string>
			<key>contentName</key>
			<string>meta.embedded.block.python</string>
			<key>end</key>
			<string>```</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.python</string>
				</dict>
			</array>
		</dict>
		<key>embedded_block_r</key>
		<dict>
			<key>begin</key>
			<string>```\s*r</string>
			<key>contentName</key>
			<string>meta.embedded.block.r</string>
			<key>end</key>
			<string>```</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.r</string>
				</dict>
			</array>
		</dict>
		<key>embedded_block_ruby</key>
		<dict>
			<key>begin</key>
			<string>```\s*ruby</string>
			<key>contentName</key>
			<string>meta.embedded.block.ruby</string>
			<key>end</key>
			<string>```</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.ruby</string>
				</dict>
			</array>
		</dict>
		<key>embedded_block_rust</key>
		<dict>
			<key>begin</key>
			<string>```\s*rust</string>
			<key>contentName</key>
			<string>meta.embedded.block.rust</string>
			<key>end</key>
			<string>```</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.rust</string>
				</dict>
			</array>
		</dict>
		<key>embedded_block_scala</key>
		<dict>
			<key>begin</key>
			<string>```\s*scala</string>
			<key>contentName</key>
			<string>meta.embedded.block.scala</string>
			<key>end</key>
			<string>```</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.scala</string>
				</dict>
			</array>
		</dict>
		<key>embedded_block_scss</key>
		<dict>
			<key>begin</key>
			<string>```\s*scss</string>
			<key>contentName</key>
			<string>meta.embedded.block.scss</string>
			<key>end</key>
			<string>```</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.css.scss</string>
				</dict>
			</array>
		</dict>
		<key>embedded_block_shellscript</key>
		<dict>
			<key>begin</key>
			<string>```\s*(shell|sh|bash|zsh|bashrc|bash_profile|bash_login|profile|bash_logout)</string>
			<key>contentName</key>
			<string>meta.embedded.block.shellscript</string>
			<key>end</key>
			<string>```</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.shell</string>
				</dict>
			</array>
		</dict>
		<key>embedded_block_sql</key>
		<dict>
			<key>begin</key>
			<string>```\s*sql</string>
			<key>contentName</key>
			<string>meta.embedded.block.sql</string>
			<key>end</key>
			<string>```</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.sql</string>
				</dict>
			</array>
		</dict>
		<key>embedded_block_typescript</key>
		<dict>
			<key>begin</key>
			<string>```\s*(typescript|ts)</string>
			<key>contentName</key>
			<string>meta.embedded.block.typescript</string>
			<key>end</key>
			<string>```</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.ts</string>
				</dict>
			</array>
		</dict>
		<key>embedded_block_typescriptreact</key>
		<dict>
			<key>begin</key>
			<string>```\s*(typescriptreact|tsx)</string>
			<key>contentName</key>
			<string>meta.embedded.block.typescriptreact</string>
			<key>end</key>
			<string>```</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.tsx</string>
				</dict>
			</array>
		</dict>
		<key>embedded_block_vs_net</key>
		<dict>
			<key>begin</key>
			<string>```\s*vs_net</string>
			<key>contentName</key>
			<string>meta.embedded.block.vs_net</string>
			<key>end</key>
			<string>```</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.asp.vb.net</string>
				</dict>
			</array>
		</dict>
		<key>embedded_block_xml</key>
		<dict>
			<key>begin</key>
			<string>```\s*xml</string>
			<key>contentName</key>
			<string>meta.embedded.block.xml</string>
			<key>end</key>
			<string>```</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>text.xml</string>
				</dict>
			</array>
		</dict>
		<key>embedded_block_xsl</key>
		<dict>
			<key>begin</key>
			<string>```\s*xsl</string>
			<key>contentName</key>
			<string>meta.embedded.block.xsl</string>
			<key>end</key>
			<string>```</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>text.xml.xsl</string>
				</dict>
			</array>
		</dict>
		<key>embedded_block_yaml</key>
		<dict>
			<key>begin</key>
			<string>```\s*yaml</string>
			<key>contentName</key>
			<string>meta.embedded.block.yaml</string>
			<key>end</key>
			<string>```</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.yaml</string>
				</dict>
			</array>
		</dict>
		<key>embeds</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#embedded_block_html</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#embedded_block_frontmatter</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#embedded_block_css</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#embedded_block_ini</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#embedded_block_java</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#embedded_block_lua</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#embedded_block_makefile</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#embedded_block_perl</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#embedded_block_r</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#embedded_block_ruby</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#embedded_block_php</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#embedded_block_sql</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#embedded_block_vs_net</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#embedded_block_xml</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#embedded_block_xsl</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#embedded_block_yaml</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#embedded_block_dosbatch</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#embedded_block_clojure</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#embedded_block_coffee</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#embedded_block_c</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#embedded_block_cpp</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#embedded_block_diff</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#embedded_block_dockerfile</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#embedded_block_go</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#embedded_block_groovy</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#embedded_block_pug</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#embedded_block_javascript</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#embedded_block_json</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#embedded_block_jsonc</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#embedded_block_less</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#embedded_block_objc</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#embedded_block_scss</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#embedded_block_perl6</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#embedded_block_powershell</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#embedded_block_python</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#embedded_block_rust</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#embedded_block_scala</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#embedded_block_shellscript</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#embedded_block_typescript</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#embedded_block_typescriptreact</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#embedded_block_csharp</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#embedded_block_fsharp</string>
				</dict>
			</array>
		</dict>
		<key>expression</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#control-logic</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#control-named</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#control</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#list</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#var</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#context</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#case</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#strike</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#markdown</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#embeds</string>
				</dict>
			</array>
		</dict>
		<key>list</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>markup.bold</string>
				</dict>
				<key>2</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#expression</string>
						</dict>
					</array>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s*(\-|\d+\.)\s+(.*)</string>
		</dict>
		<key>markdown</key>
		<dict>
			<key>begin</key>
			<string>OPEN_MARKDOWN</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>entity.name.namespace</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>meta.embedded.block.markdown</string>
			<key>end</key>
			<string>CLOSE_MARKDOWN</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>entity.name.namespace</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>text.html.markdown</string>
				</dict>
			</array>
		</dict>
		<key>strike</key>
		<dict>
			<key>match</key>
			<string>^\s*--.*</string>
			<key>name</key>
			<string>markup.deleted</string>
		</dict>
		<key>var</key>
		<dict>
			<key>match</key>
			<string>\$[A-Za-z][A-Za-z0-9.\[\]'"]*</string>
			<key>name</key>
			<string>variable</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.uflow</string>
	<key>uuid</key>
	<string>B7A8C571-820A-4958-A997-76DFD822B0FE</string>
</dict>
</plist>
